#!/bin/sh
### BEGIN INIT INFO
# Provides:          ddnspod
# Required-Start:    $remote_fs
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the dynamic service supported by DNSPod.
### END INIT INFO

case "$1" in
start)
        start-stop-daemon --start --background --exec /opt/PyDdnsPod/PyDDNSPod.py
;;
stop)
        start-stop-daemon --stop --name PyDDNSPod.py
esac
